# Generated by Django 5.0.4 on 2024-04-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeName', models.TextField(max_length=250)),
                ('EmployeeSalary', models.FloatField()),
                ('EmployeeAddress', models.TextField(max_length=1000)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
