# Generated by Django 5.0.4 on 2024-04-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=40)),
                ('Email_id', models.EmailField(max_length=254)),
                ('pass1', models.CharField(max_length=30)),
            ],
        ),
    ]
